/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InscripcionController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Curso;
import model.Estudiante;
import model.Inscripcion;
import model.Tematica;

/**
 *
 * @author tomichveronica
 */
public class PantallaInscripcion extends javax.swing.JFrame {

    private final InscripcionController inscripcionController;
    private Estudiante estudiante;
    private TablaCursosModel tablaCursosModel = new TablaCursosModel(new ArrayList<>());

    /**
     * Creates new form PantallaInscripcion
     *
     * @param inscripcionController
     */
    public PantallaInscripcion(InscripcionController inscripcionController) {
        initComponents();

        rbtEstudianteRegistrado.setSelected(true);
        this.panDatosEstudiante.setVisible(false);

        this.inscripcionController = inscripcionController;
        this.cargarTematicas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        panelEstudiante = new javax.swing.JPanel();
        rbtEstudianteRegistrado = new javax.swing.JRadioButton();
        rbtEstudianteNoRegistrado = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lblIngreseEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JToggleButton();
        panDatosEstudiante = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        panelCursos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbxTematicas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnInscribirse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmTitulo"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Formulario Inscripción a un Curso");
        jLabel1.setName("lblTitulo"); // NOI18N

        panelEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiante"));

        buttonGroup1.add(rbtEstudianteRegistrado);
        rbtEstudianteRegistrado.setText("Estudiante Registrado");
        rbtEstudianteRegistrado.setToolTipText("");
        rbtEstudianteRegistrado.setName("rbtEstudianteRegistrado"); // NOI18N
        rbtEstudianteRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEstudianteRegistradoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtEstudianteNoRegistrado);
        rbtEstudianteNoRegistrado.setText("Estudiante No Registrado");
        rbtEstudianteNoRegistrado.setName("rbtEstudianteNoRegistrado"); // NOI18N
        rbtEstudianteNoRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEstudianteNoRegistradoActionPerformed(evt);
            }
        });

        lblIngreseEmail.setText("Ingrese su e-mail:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblApellido.setText("Apellido:");

        txtApellido.setText("Apellido");

        txtNombre.setText("Nombre");

        javax.swing.GroupLayout panDatosEstudianteLayout = new javax.swing.GroupLayout(panDatosEstudiante);
        panDatosEstudiante.setLayout(panDatosEstudianteLayout);
        panDatosEstudianteLayout.setHorizontalGroup(
            panDatosEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosEstudianteLayout.createSequentialGroup()
                .addGroup(panDatosEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosEstudianteLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(panDatosEstudianteLayout.createSequentialGroup()
                        .addComponent(lblApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panDatosEstudianteLayout.setVerticalGroup(
            panDatosEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosEstudianteLayout.createSequentialGroup()
                .addGroup(panDatosEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDatosEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido)))
        );

        javax.swing.GroupLayout panelEstudianteLayout = new javax.swing.GroupLayout(panelEstudiante);
        panelEstudiante.setLayout(panelEstudianteLayout);
        panelEstudianteLayout.setHorizontalGroup(
            panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstudianteLayout.createSequentialGroup()
                .addGroup(panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstudianteLayout.createSequentialGroup()
                        .addGroup(panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEstudianteLayout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel2))
                            .addGroup(panelEstudianteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbtEstudianteRegistrado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIngreseEmail))
                    .addGroup(panelEstudianteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbtEstudianteNoRegistrado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstudianteLayout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(panelEstudianteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panDatosEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEstudianteLayout.setVerticalGroup(
            panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstudianteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIngreseEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtEstudianteRegistrado)
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtEstudianteNoRegistrado)
                    .addComponent(panDatosEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCursos.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Vigentes"));

        jLabel3.setText("Temáticas");

        cbxTematicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTematicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTematicasActionPerformed(evt);
            }
        });

        tblCursos.setModel(tablaCursosModel);
        jScrollPane1.setViewportView(tblCursos);

        javax.swing.GroupLayout panelCursosLayout = new javax.swing.GroupLayout(panelCursos);
        panelCursos.setLayout(panelCursosLayout);
        panelCursosLayout.setHorizontalGroup(
            panelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(panelCursosLayout.createSequentialGroup()
                        .addGroup(panelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbxTematicas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCursosLayout.setVerticalGroup(
            panelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTematicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnInscribirse.setText("Inscribirse");
        btnInscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInscribirse)
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnInscribirse)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(panelEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtEstudianteRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEstudianteRegistradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtEstudianteRegistradoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String email = this.txtEmail.getText();

        this.actualizarEstudianteInscripcion(email);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbxTematicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTematicasActionPerformed
        Tematica tematica = (Tematica) this.cbxTematicas.getSelectedItem();
        this.cargarCursos(tematica);
    }//GEN-LAST:event_cbxTematicasActionPerformed

    private void btnInscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirseActionPerformed
        Curso curso = this.obtenerCursoSeleccionado();
        this.inscripcionController.guardarInscripcion(estudiante, curso);
    }//GEN-LAST:event_btnInscribirseActionPerformed

    private void rbtEstudianteNoRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEstudianteNoRegistradoActionPerformed
        this.rbtEstudianteRegistrado.setSelected(true);

        this.inscripcionController.mostrarRegistracion();
    }//GEN-LAST:event_rbtEstudianteNoRegistradoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInscribirse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> cbxTematicas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblIngreseEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panDatosEstudiante;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCursos;
    private javax.swing.JPanel panelEstudiante;
    private javax.swing.JRadioButton rbtEstudianteNoRegistrado;
    private javax.swing.JRadioButton rbtEstudianteRegistrado;
    private javax.swing.JTable tblCursos;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables

    private void cargarTematicas() {
        this.cbxTematicas.removeAllItems();
        List<Tematica> tematicas = this.inscripcionController.buscarTematicas();
        this.cbxTematicas.setModel(new DefaultComboBoxModel(tematicas.toArray()));

        this.cargarCursos(tematicas.get(0));
    }

    private void cargarCursos(Tematica tematica) {
        List<Curso> cursos = this.inscripcionController.buscarCursos(tematica);
        this.tablaCursosModel.setCursos(cursos);
        this.tablaCursosModel.fireTableDataChanged();
        this.tblCursos.updateUI();
    }

    public Curso obtenerCursoSeleccionado() {
        Curso retorno = null;
        int filaSeleccionada = tblCursos.getSelectedRow();

        // validamos que haya una fila seleccionada
        if (filaSeleccionada >= 0) {
            retorno = tablaCursosModel.obtenerCursoEn(filaSeleccionada);
        }

        return retorno;
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public boolean mostrarMensajeConfirmacionGuardado() {
        String mensaje = "Esta seguro que desea inscribirse al curso?";
        String titulo = "Confirmación";
        int generaInscripcion = JOptionPane.showConfirmDialog(null, mensaje, titulo, JOptionPane.YES_OPTION);
        return generaInscripcion == JOptionPane.YES_OPTION;
    }

    public boolean mostrarMensajeConfirmacionGuardadoCondicional() {
        String mensaje = "Esta seguro que desea inscribirse al curso de forma condicional?";
        String titulo = "Confirmación";
        int generaInscripcion = JOptionPane.showConfirmDialog(null, mensaje, titulo, JOptionPane.YES_OPTION);
        return generaInscripcion == JOptionPane.YES_OPTION;
    }

    public void actualizarEstudianteInscripcion(String email) {
        this.estudiante = this.inscripcionController.buscarEstudiante(email);

        if (estudiante != null) {
            txtNombre.setText(estudiante.getNombre());
            txtApellido.setText(estudiante.getApellido());
            txtEmail.setText(estudiante.getEmail());
            this.panDatosEstudiante.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No fue posible encontrar el estudiante buscado");
            this.panDatosEstudiante.setVisible(false);
        }
    }
}
